name: tensorflow-2.16-cuda12
channels:
- conda-forge
- anaconda
dependencies:
- python=3.10
- pip=22.3.1
- pandas=2.2.2
# - numpy=1.26.4/
- scipy~=1.14.0
- pip:
  - mldesigner==0.1.0b12
  - azure-ai-ml >=1.2.0
  - azure-identity
  - mldesigner
  - numpy==1.26.4
  - setuptools==72.1.0
  - wheel==0.44.0
  - matplotlib~=3.5.0
  - psutil~=5.8.0
  - tqdm~=4.66.3
  - ipykernel~=6.20.2
  - tensorboard~=2.16.0
  - tensorflow[and-cuda]==2.16.2
  - tensorflow-datasets~=4.9.0        
  - keras==3.3.2
  - tf-keras==2.16.0
  - debugpy~=1.6.3
  - cryptography>=41.0.4
  - idna>=3.7
  - scikit-learn==1.2.2